cursor #1c1b19
cursor_text_color #484743

foreground            #1c1b19
background            #fdf9f4
selection_foreground  #ffffff
selection_background  #cbc7b5
url_color             #625f49

color0   #141311
color1   #793830
color2   #295f21
color3   #998626
color4   #66634b
color5   #adab9f
color6   #625f49
color7   #232322
color8   #010000
color9   #a35d54
color10  #498c3f
color11  #a59331
color12  #747055
color13  #adab9f
color14  #7f7d6f
color15  #bfbebb
