cursor #1b1c1b
cursor_text_color #434844

foreground            #1b1c1b
background            #fbf9f7
selection_foreground  #ffffff
selection_background  #c1c8c1
url_color             #4e6054

color0   #fbf9f7
color1   #794430
color2   #215f22
color3   #7c7201
color4   #506457
color5   #66796c
color6   #4e6054
color7   #222322
color8   #b9bcba
color9   #99614c
color10  #3f8c40
color11  #978d23
color12  #576e5f
color13  #6c7c71
color14  #717c75
color15  #bbbfbc
