cursor #ffffff
cursor_text_color #aaaaaa

foreground            #ffffff
background            #121113
selection_foreground  #121113
selection_background  #5f8787
url_color             #e78a53

color0   #1c1b1d
color1   #ff534b
color2   #6de753
color3   #ffde4b
color4   #db7132
color5   #b96a3d
color6   #e78a53
color7   #f2e6df
color8   #514a46
color9   #ff8984
color10  #a1ff8c
color11  #ffea8c
color12  #fea773
color13  #ffb78c
color14  #ffd0b5
color15  #fff9f6
