# Font-Family
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

# Font size (in pts)
font_size 12.0

background_opacity 1

# Tabs
tab_bar_style powerline
tab_powerline_style round
tab_bar_edge bottom
# active_tab_foreground   #000
# active_tab_background   #FFDDAB
active_tab_font_style   bold
# inactive_tab_foreground #444
# inactive_tab_background #eee
inactive_tab_font_style normal

hide_window_decorations yes
window_padding_width 0

# git clone --depth 1 https://github.com/dexpota/kitty-themes.git ~/.config/kitty/kitty-themes
# kitty +kitten themes
include theme.conf


mouse_hide_wait -3.0
