# available fonts: $ kitty list-fonts
font_family        JetBrains Mono
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          12

copy_on_select yes

map ctrl+shift+s save_as_session ~/.config/kitty/last_session.session
# kitty --session ~/.config/kitty/last_session.session

# -- window --
window_margin_width 10 15
window_resize_step_cells 5
window_resize_step_lines 2
confirm_os_window_close 0

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# window management
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# layout management
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# tab bar customization
tab_bar_style separator
#tab_powerline_style separator
tab_separator " "
tab_bar_edge bottom
tab_bar_align center
active_tab_font_style   bold
inactive_tab_font_style normal
tab_activity_symbol *
tab_title_template        "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370} {fmt.fg.red}{activity_symbol}{fmt.fg._abb2bf}{index}: {title}{' [{}]'.format(num_windows) if num_windows > 1 else ''} {fmt.fg._5c6370}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._282c34}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._282c34} {fmt.fg.red}{activity_symbol}{fmt.fg.white}{index}: {title}{' [{}]'.format(num_windows) if num_windows > 1 else ''} {fmt.fg._282c34}{fmt.bg.default} "

# Selection Colors
#selection_foreground     #ebdbb2
#selection_background     #d65d0e

# -- color scheme --
background_opacity 1
background_blur 0

# -- misc settings --
enable_audio_bell no
force_ltr no
detect_urls yes


# BEGIN_KITTY_THEME
# GitHub Dark High Contrast
include current-theme.conf
# END_KITTY_THEME
